app1/urls.py
from app1.views import *
from django.urls import path
app_name='beta'

urlpatterns=[
    path('pakistan/',pakistan,name='pakistan'),
    
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='baap'

urlpatterns=[

    path('india/',india,name='india'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def pakistan(request):
    return render(request,'pakistan.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def india(request):
    return render(request,'india.html')

templates/india.html
<!DOCTYPE html>
<html>
<head>
    <title>CONVERSATION BETWEEN TWO COUNTRYS</title>
</head>
<body>
    <center>
        <h1>INDIA ME TOH FOG CHAL RHA HAI</h1>
        <h1><a href="{% url 'beta:pakistan' %}">BACK TO HOME PAGE</a></h1>
    </center>
</body>
</html>

templates/pakistan.html
<!DOCTYPE html>
<html>
<head>
    <title>CONVERSATION BETWEEN TWO COUNTRYS</title>
</head>
<body>
    <center>
        <h1>INDIA ME KYA CHAL RHA HAI</h1>
        <h1><a href="{% url 'baap:india' %}"><h3>RESPONSE TO INDIA PAGE</h3></a></h1>
    </center>
</body>
</html>